version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Workspaces: ensure it checks root pnpm-lock.yaml
    allow:
      - dependency-type: "direct"
